# Generated by Django 3.2.12 on 2022-12-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='last_name',
        ),
    ]
