# Generated by Django 3.2.12 on 2022-12-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_applicant_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
