# Generated by Django 3.2.12 on 2022-12-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20221204_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
